name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run `nix build`
      run: nix build .

  flake-check:
    name: Check Flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main

  check:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run flake check (checks all ghc versions)
      run: nix flake check
    - name: Run library tests (latest versions)
      run: nix develop .#ci -c tst
    - name: Run doc tests (latest versions)
      run: nix develop .#ci -c dtst
    - name: check formatting (current source)
      run: nix develop .#ci -c format-check
